################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/BaseDMA.cpp \
../src/LacksDMA.cpp \
../src/RatedPlayer.cpp \
../src/Student.cpp \
../src/TableTennisPlayer.cpp \
../src/Test-C++.cpp \
../src/append.cpp \
../src/arrayone.cpp \
../src/bclx_15_1.cpp \
../src/binarytest.cpp \
../src/chartype.cpp \
../src/cinexcp.cpp \
../src/comstr1.cpp \
../src/copychar.cpp \
../src/defaults.cpp \
../src/divide.cpp \
../src/error5.cpp \
../src/formore.cpp \
../src/funadap.cpp \
../src/get_fun.cpp \
../src/getinfo.cpp \
../src/iftest.cpp \
../src/inserts.cpp \
../src/instr.cpp \
../src/instr3.cpp \
../src/iomanip.cpp \
../src/limits.cpp \
../src/list.cpp \
../src/listrmv.cpp \
../src/manyfrnd.cpp \
../src/multmap.cpp \
../src/mytime0.cpp \
../src/namesp.cpp \
../src/namessp.cpp \
../src/nested.cpp \
../src/newexcp.cpp \
../src/outfile.cpp \
../src/peeker.cpp \
../src/randomtest.cpp \
../src/readfile.cpp \
../src/rp17-8.cpp \
../src/rtti2.cpp \
../src/setf.cpp \
../src/setf2.cpp \
../src/setops.cpp \
../src/showpt.cpp \
../src/stacktem.cpp \
../src/stkoptr1.cpp \
../src/stocks.cpp \
../src/str1.cpp \
../src/strfile.cpp \
../src/strgstl.cpp \
../src/stringtest.cpp \
../src/strout.cpp \
../src/strquote.cpp \
../src/strtref.cpp \
../src/structtest.cpp \
../src/tempmemb.cpp \
../src/tempnamtest.cpp \
../src/testclass.cpp \
../src/textin.cpp \
../src/truncate.cpp \
../src/tv.cpp \
../src/twod.cpp \
../src/twoswap.cpp \
../src/twotemps.cpp \
../src/use_stuc.cpp \
../src/usealgo.cpp \
../src/usetime0.cpp \
../src/usett1.cpp \
../src/usevector.cpp \
../src/valarraytest.cpp \
../src/valvect.cpp \
../src/vect1.cpp \
../src/vect3.cpp \
../src/vector.cpp \
../src/vslice.cpp \
../src/width.cpp \
../src/workermi.cpp \
../src/workmi.cpp \
../src/write.cpp 

OBJS += \
./src/BaseDMA.o \
./src/LacksDMA.o \
./src/RatedPlayer.o \
./src/Student.o \
./src/TableTennisPlayer.o \
./src/Test-C++.o \
./src/append.o \
./src/arrayone.o \
./src/bclx_15_1.o \
./src/binarytest.o \
./src/chartype.o \
./src/cinexcp.o \
./src/comstr1.o \
./src/copychar.o \
./src/defaults.o \
./src/divide.o \
./src/error5.o \
./src/formore.o \
./src/funadap.o \
./src/get_fun.o \
./src/getinfo.o \
./src/iftest.o \
./src/inserts.o \
./src/instr.o \
./src/instr3.o \
./src/iomanip.o \
./src/limits.o \
./src/list.o \
./src/listrmv.o \
./src/manyfrnd.o \
./src/multmap.o \
./src/mytime0.o \
./src/namesp.o \
./src/namessp.o \
./src/nested.o \
./src/newexcp.o \
./src/outfile.o \
./src/peeker.o \
./src/randomtest.o \
./src/readfile.o \
./src/rp17-8.o \
./src/rtti2.o \
./src/setf.o \
./src/setf2.o \
./src/setops.o \
./src/showpt.o \
./src/stacktem.o \
./src/stkoptr1.o \
./src/stocks.o \
./src/str1.o \
./src/strfile.o \
./src/strgstl.o \
./src/stringtest.o \
./src/strout.o \
./src/strquote.o \
./src/strtref.o \
./src/structtest.o \
./src/tempmemb.o \
./src/tempnamtest.o \
./src/testclass.o \
./src/textin.o \
./src/truncate.o \
./src/tv.o \
./src/twod.o \
./src/twoswap.o \
./src/twotemps.o \
./src/use_stuc.o \
./src/usealgo.o \
./src/usetime0.o \
./src/usett1.o \
./src/usevector.o \
./src/valarraytest.o \
./src/valvect.o \
./src/vect1.o \
./src/vect3.o \
./src/vector.o \
./src/vslice.o \
./src/width.o \
./src/workermi.o \
./src/workmi.o \
./src/write.o 

CPP_DEPS += \
./src/BaseDMA.d \
./src/LacksDMA.d \
./src/RatedPlayer.d \
./src/Student.d \
./src/TableTennisPlayer.d \
./src/Test-C++.d \
./src/append.d \
./src/arrayone.d \
./src/bclx_15_1.d \
./src/binarytest.d \
./src/chartype.d \
./src/cinexcp.d \
./src/comstr1.d \
./src/copychar.d \
./src/defaults.d \
./src/divide.d \
./src/error5.d \
./src/formore.d \
./src/funadap.d \
./src/get_fun.d \
./src/getinfo.d \
./src/iftest.d \
./src/inserts.d \
./src/instr.d \
./src/instr3.d \
./src/iomanip.d \
./src/limits.d \
./src/list.d \
./src/listrmv.d \
./src/manyfrnd.d \
./src/multmap.d \
./src/mytime0.d \
./src/namesp.d \
./src/namessp.d \
./src/nested.d \
./src/newexcp.d \
./src/outfile.d \
./src/peeker.d \
./src/randomtest.d \
./src/readfile.d \
./src/rp17-8.d \
./src/rtti2.d \
./src/setf.d \
./src/setf2.d \
./src/setops.d \
./src/showpt.d \
./src/stacktem.d \
./src/stkoptr1.d \
./src/stocks.d \
./src/str1.d \
./src/strfile.d \
./src/strgstl.d \
./src/stringtest.d \
./src/strout.d \
./src/strquote.d \
./src/strtref.d \
./src/structtest.d \
./src/tempmemb.d \
./src/tempnamtest.d \
./src/testclass.d \
./src/textin.d \
./src/truncate.d \
./src/tv.d \
./src/twod.d \
./src/twoswap.d \
./src/twotemps.d \
./src/use_stuc.d \
./src/usealgo.d \
./src/usetime0.d \
./src/usett1.d \
./src/usevector.d \
./src/valarraytest.d \
./src/valvect.d \
./src/vect1.d \
./src/vect3.d \
./src/vector.d \
./src/vslice.d \
./src/width.d \
./src/workermi.d \
./src/workmi.d \
./src/write.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


